language: java

jdk:
  - openjdk8
  - oraclejdk8

env:
  - SPRING_BOOT_VERSION=1.5.19.RELEASE
  - SPRING_BOOT_VERSION=2.1.3.RELEASE

#services:
#  - docker

install: true
script: mvn -B clean package
  -Dspring.boot.version=$SPRING_BOOT_VERSION
  -Dmaven.javadoc.skip=true -Dmaven.source.skip=true

jobs:
  include:
    - stage: test
    - stage: sonarcloud
      git:
        depth: false
      jdk: openjdk8
      env: SPRING_BOOT_VERSION=2.1.3.RELEASE
      script:
        - SONAR_PARAMS="";
          if [ "${TRAVIS_PULL_REQUEST:-false}" != "false" ]; then
            SONAR_PARAMS="$SONAR_PARAMS -Dsonar.pullrequest.key=${TRAVIS_PULL_REQUEST}";
            SONAR_PARAMS="$SONAR_PARAMS -Dsonar.pullrequest.branch=${TRAVIS_PULL_REQUEST_BRANCH}";
            SONAR_PARAMS="$SONAR_PARAMS -Dsonar.pullrequest.base=${TRAVIS_BRANCH}";
            SONAR_PARAMS="$SONAR_PARAMS -Dsonar.pullrequest.provider=github";
            SONAR_PARAMS="$SONAR_PARAMS -Dsonar.pullrequest.github.repository=${TRAVIS_REPO_SLUG}";
          else
            if  [ -z "$TRAVIS_TAG" -a "${TRAVIS_BRANCH:-master}" != "master" ]; then
              SONAR_PARAMS="$SONAR_PARAMS -Dsonar.branch.name=${TRAVIS_BRANCH}";
              if  [ -z "$TRAVIS_TAG" -a "${TRAVIS_BRANCH:-develop}" != "develop" ]; then
                SONAR_PARAMS="$SONAR_PARAMS -Dsonar.branch.target=master";
              fi;
            fi;
          fi;
        - echo "$SONAR_PARAMS"
        - mvn -B verify
          -Dspring.boot.version=$SPRING_BOOT_VERSION
          -Dsonar.login="${SONAR_TOKEN}"
          $SONAR_PARAMS

cache:
  directories:
    - $HOME/.m2
